ALTER TABLE student_case_progress
  ADD COLUMN IF NOT EXISTS responses JSONB DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS score INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS completed BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP WITH TIME ZONE;
